# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  pull_request:
    branches: [ "develop", "release" ]

jobs:
  build-and-test:
    runs-on: macos-26
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData/TrackChart-*
          key: deriveddata-macos26-${{ hashFiles('TrackChart.xcodeproj/project.pbxproj') }}-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            deriveddata-macos26-

      - name: Select Xcode 26.0.1
        run: sudo xcode-select -switch /Applications/Xcode_26.0.1.app

      - name: Build & test macOS
        run: |
          set -o pipefail
          xcodebuild test \
            -project TrackChart.xcodeproj \
            -scheme CI_macOS \
            -testPlan CI_macOS \
            -destination 'platform=macOS,arch=arm64' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            | xcbeautify --is-ci
